# Importation des éléments d'intérêt du module
# Vulnerabilities — DEFAULT_CONFIG réexporté sous un nom explicite pour éviter
# la collision avec son homonyme de processing (importations étoilées interdites)
from .vulnerabilities import (
    VulnerabilityConfig,
    DEFAULT_CONFIG as VULNERABILITY_DEFAULT_CONFIG,
    VulnerabilityMetric,
    individual_partner_expr,
    VulnerabilityReport,
    InputReport,
    CoverageReport,
    AggregateQualityReport,
    ScoreDistributionReport,
    DriftReport,
    compute_input_report,
    compute_coverage_report,
    compute_quality_report,
    compute_distribution_reports,
    compute_drift_report,
    compute_shares_frame,
    missing_aggregate_cells,
    log_vulnerability_artifacts,
    HerfindahlHirschmanIndex,
    ConcentrationDependencyIndex2,
    ConcentrationDependencyIndex3,
    DEFAULT_METRIC_CLASSES,
    default_metrics,
    compute_vulnerabilities,
    read_previous_result,
    run_vulnerabilities,
    run_vulnerabilities_incremental,
)
# Processing (redressement BACI) — idem pour son propre DEFAULT_CONFIG
from .processing import (
    ComtradeSchema,
    BaciConfig,
    DEFAULT_CONFIG as BACI_DEFAULT_CONFIG,
    build_gravity_data,
    build_mirror_flows,
    infer_import_valuation_regime,
    world_median_unit_values,
    required_columns,
    TonnageConverter,
    CifGravityModel,
    Fobizer,
    ReportingQualityModel,
    QualityResult,
    MirrorReconciler,
    AreaNesReallocator,
    TonnageReport,
    GravityReport,
    FobisationReport,
    MirrorReport,
    QualityReport,
    NesReport,
    aggregate_measures,
    HsHarmonizer,
    HsHarmonizationReport,
    build_conversion_map,
    resolve_vintage,
    BaciReport,
    run_baci,
)

# Réexport des éléments d'intérêt du module
__all__ = [
    # Vulnerabilities
    "VulnerabilityConfig",
    "VULNERABILITY_DEFAULT_CONFIG",
    "VulnerabilityMetric",
    "individual_partner_expr",
    "VulnerabilityReport",
    "InputReport",
    "CoverageReport",
    "AggregateQualityReport",
    "ScoreDistributionReport",
    "DriftReport",
    "compute_input_report",
    "compute_coverage_report",
    "compute_quality_report",
    "compute_distribution_reports",
    "compute_drift_report",
    "compute_shares_frame",
    "missing_aggregate_cells",
    "log_vulnerability_artifacts",
    "HerfindahlHirschmanIndex",
    "ConcentrationDependencyIndex2",
    "ConcentrationDependencyIndex3",
    "DEFAULT_METRIC_CLASSES",
    "default_metrics",
    "compute_vulnerabilities",
    "read_previous_result",
    "run_vulnerabilities",
    "run_vulnerabilities_incremental",
    # Processing (redressement BACI)
    "ComtradeSchema",
    "BaciConfig",
    "BACI_DEFAULT_CONFIG",
    "build_gravity_data",
    "build_mirror_flows",
    "infer_import_valuation_regime",
    "world_median_unit_values",
    "required_columns",
    "TonnageConverter",
    "CifGravityModel",
    "Fobizer",
    "ReportingQualityModel",
    "QualityResult",
    "MirrorReconciler",
    "AreaNesReallocator",
    "TonnageReport",
    "GravityReport",
    "FobisationReport",
    "MirrorReport",
    "QualityReport",
    "NesReport",
    "aggregate_measures",
    "HsHarmonizer",
    "HsHarmonizationReport",
    "build_conversion_map",
    "resolve_vintage",
    "BaciReport",
    "run_baci",
]
