"""Project configuration access and pure helpers on the nomenclature vintages.

Configuration access: :func:`load_parameters` reproduces the Kedro
configuration merge (``OmegaConfigLoader`` built with the very arguments of
``kedro_pipeline.settings``) for the code that runs outside a Kedro session —
the transitional scripts. The environment is ``KEDRO_ENV`` (``local`` by
default), as for ``kedro run``. :func:`experiment_name` gives the MLflow
experiment of a block of steps and :func:`active_targets` the enabled BACI
targets.

The single source of truth of the vintages is ``runtime.NOMENCLATURES.HS``: a mapping from HS
vintage label to its entry-into-force year. Every function here is pure (no
I/O, no environment). The partner step stamps ``classification`` /
``hs_vintage`` / ``in_force`` on its rows with them, the historical rows being
the flows of later years converted into an older vintage
(:func:`requested_vintages`, :func:`first_historical_year`); the SQL macros
generated by :func:`nomenclature_macros_sql` evaluate the very same rules
inside DuckDB (serving layer, synthesis join, table migration).
"""
# Importation des modules
# Modules de base
import copy
import functools
import os
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional, Tuple

# Variable d'environnement de sélection de l'environnement Kedro (comme `kedro run`)
KEDRO_ENV_VARIABLE = "KEDRO_ENV"
# Variable d'environnement prioritaire sur le nom d'expérience MLflow configuré
EXPERIMENT_NAME_VARIABLE = "MLFLOW_EXPERIMENT_NAME"
# Racine du dépôt : la configuration est cherchée à côté du paquet, puis dans le
# répertoire courant (paquet installé hors du dépôt)
_REPO_ROOT = Path(__file__).resolve().parents[1]


# Fonction de tri des millésimes par année d'entrée en vigueur
def _sorted_vintages(nomenclatures: Mapping[str, int]) -> List[Tuple[str, int]]:
    """Return the ``(vintage, entry_year)`` pairs sorted by entry year.

    Args:
        nomenclatures: Mapping vintage label -> entry-into-force year.

    Returns:
        Pairs sorted by increasing entry year (ties broken by label).

    Raises:
        ValueError: If the mapping is empty.
    """
    # Vérification des arguments
    if not nomenclatures:
        raise ValueError("nomenclatures is empty: runtime.NOMENCLATURES.HS is required")
    return sorted(
        ((str(label), int(year)) for label, year in nomenclatures.items()),
        key=lambda item: (item[1], item[0]),
    )


# Fonction de détermination du millésime en vigueur une année donnée
def vintage_in_force(year: int, nomenclatures: Mapping[str, int]) -> str:
    """Return the HS vintage in force for ``year``.

    Args:
        year: Reference year.
        nomenclatures: Mapping vintage label -> entry-into-force year
            (``runtime.NOMENCLATURES.HS``).

    Returns:
        Label of the most recent vintage whose entry year is ``<= year``.

    Raises:
        ValueError: If ``year`` precedes the first vintage, or if the mapping
            is empty.

    Examples:
        >>> hs = {"HS1992": 1988, "HS1996": 1996, "HS2002": 2002, "HS2022": 2022}
        >>> vintage_in_force(1990, hs), vintage_in_force(2001, hs), vintage_in_force(2024, hs)
        ('HS1992', 'HS1996', 'HS2022')
    """
    vintages = _sorted_vintages(nomenclatures)
    # Dernier millésime entré en vigueur au plus tard l'année demandée
    eligible = [label for label, entry in vintages if entry <= int(year)]
    if not eligible:
        raise ValueError(
            f"No HS vintage in force in {year}: the first one enters into force "
            f"in {vintages[0][1]}"
        )
    return eligible[-1]


# Fonction de listage des millésimes historiques d'une année
def historical_vintages(year: int, nomenclatures: Mapping[str, int]) -> List[str]:
    """Return the vintages V with ``entry(V) <= year``, except the one in force.

    Args:
        year: Reference year.
        nomenclatures: Mapping vintage label -> entry-into-force year.

    Returns:
        Historical vintages, oldest first (empty when only one applies).

    Raises:
        ValueError: If ``year`` precedes the first vintage.

    Examples:
        >>> hs = {"HS1992": 1988, "HS1996": 1996, "HS2002": 2002, "HS2022": 2022}
        >>> historical_vintages(2024, hs)
        ['HS1992', 'HS1996', 'HS2002']
        >>> historical_vintages(1990, hs)
        []
    """
    in_force = vintage_in_force(year, nomenclatures)
    return [
        label
        for label, entry in _sorted_vintages(nomenclatures)
        if entry <= int(year) and label != in_force
    ]


# Fonction de sélection des millésimes historiques demandés
def requested_vintages(spec: Any, nomenclatures: Mapping[str, int]) -> List[str]:
    """Resolve the historical vintages requested by the configuration.

    A historical vintage is one into which the flows of later years are
    converted, so that a product keeps a fixed nomenclature over a long time
    series. The most recent vintage of the referential is never historical (no
    year is ever converted into it from a later one): it is left out of
    ``"all"`` and rejected when listed explicitly.

    Args:
        spec: ``"all"`` (every vintage but the most recent), a list of vintage
            labels, or an empty list / ``None`` (no historical rows).
        nomenclatures: Mapping vintage label -> entry-into-force year.

    Returns:
        The requested vintages, oldest first.

    Raises:
        ValueError: If ``spec`` is an unknown string, names a vintage absent
            from the referential, or names the most recent vintage.

    Examples:
        >>> hs = {"HS1992": 1988, "HS2017": 2017, "HS2022": 2022}
        >>> requested_vintages("all", hs), requested_vintages(["HS2017"], hs), requested_vintages([], hs)
        (['HS1992', 'HS2017'], ['HS2017'], [])
    """
    vintages = [label for label, _ in _sorted_vintages(nomenclatures)]
    eligible = vintages[:-1]
    # Aucun millésime historique demandé
    if spec is None or (isinstance(spec, (list, tuple)) and not spec):
        return []
    if isinstance(spec, str):
        if spec != "all":
            raise ValueError(f"VINTAGES must be 'all' or a list of vintages, got {spec!r}")
        return eligible
    # Liste explicite : millésimes connus, le plus récent exclu
    unknown = sorted(set(map(str, spec)) - set(vintages))
    if unknown:
        raise ValueError(f"Unknown HS vintages {unknown}: expected some of {vintages}")
    if vintages[-1] in set(map(str, spec)):
        raise ValueError(
            f"{vintages[-1]} is the most recent vintage: no later year is ever "
            "converted into it, it cannot be historical"
        )
    return [label for label in eligible if label in set(map(str, spec))]


# Fonction de détermination de la première année historique d'un millésime
def first_historical_year(vintage: str, nomenclatures: Mapping[str, int]) -> int:
    """Return the first year whose flows are converted into ``vintage``.

    It is the entry-into-force year of the next vintage: before it, the codes
    of ``vintage`` are the declared ones (rows in force).

    Args:
        vintage: Vintage label.
        nomenclatures: Mapping vintage label -> entry-into-force year.

    Returns:
        The entry year of the vintage following ``vintage``.

    Raises:
        ValueError: If ``vintage`` is unknown or is the most recent one.

    Examples:
        >>> first_historical_year("HS2017", {"HS2017": 2017, "HS2022": 2022})
        2022
    """
    vintages = _sorted_vintages(nomenclatures)
    labels = [label for label, _ in vintages]
    if vintage not in labels:
        raise ValueError(f"Unknown HS vintage {vintage!r}: expected one of {labels}")
    position = labels.index(vintage)
    if position == len(labels) - 1:
        raise ValueError(f"{vintage} is the most recent vintage: it has no historical year")
    return vintages[position + 1][1]


# Fonction de détermination du millésime SH de rattachement d'une classification
def hs_vintage_of(classification: str, year: int, nomenclatures: Mapping[str, int]) -> str:
    """Return the HS vintage a classification is attached to in ``year``.

    An HS classification is its own vintage; a Combined Nomenclature
    classification (``CN<year>``) is attached to the HS vintage in force that
    year, since its first six digits are HS codes of that vintage.

    Args:
        classification: ``"HSxxxx"`` or ``"CN<year>"``.
        year: Reference year.
        nomenclatures: Mapping vintage label -> entry-into-force year.

    Returns:
        The HS vintage label.

    Examples:
        >>> hs = {"HS2017": 2017, "HS2022": 2022}
        >>> hs_vintage_of("CN2019", 2019, hs), hs_vintage_of("HS2017", 2023, hs)
        ('HS2017', 'HS2017')
    """
    if str(classification).startswith("CN"):
        return vintage_in_force(year, nomenclatures)
    return str(classification)


# Fonction d'attribution de la nomenclature d'un code produit
def classification_of(product: str, year: int, nomenclatures: Mapping[str, int]) -> str:
    """Return the classification a product code belongs to in ``year``.

    Two-, four- and six-digit codes are HS codes of the vintage in force;
    eight-digit codes are Combined Nomenclature codes of that year.

    Args:
        product: Product code, as text or integer (see :func:`product_code`).
        year: Reference year.
        nomenclatures: Mapping vintage label -> entry-into-force year.

    Returns:
        ``"HSxxxx"`` for 2/4/6-digit codes, ``"CN<year>"`` for 8-digit codes.

    Raises:
        ValueError: If ``year`` precedes the first vintage.

    Examples:
        >>> hs = {"HS1992": 1988, "HS2017": 2017, "HS2022": 2022}
        >>> classification_of("854110", 2019, hs), classification_of("85411000", 2019, hs)
        ('HS2017', 'CN2019')
    """
    if len(product_code(product)) == 8:
        return f"CN{int(year)}"
    return vintage_in_force(year, nomenclatures)


# Fonction de restitution d'un code produit stocké en entier
def product_code(product: object) -> str:
    """Return a product code as text, restoring the leading zero lost by integer storage.

    Comext product codes are read as ``BIGINT`` by the download step, so
    chapters 01-09 lose their leading zero (``01012100`` -> ``1012100``). HS
    and CN codes have an even length (2, 4, 6, 8 digits): a numeric code of odd
    length is therefore left-padded by one zero. Non-numeric codes are kept.

    Args:
        product: Product code, as text or integer.

    Returns:
        The code as text, with its leading zero restored.

    Examples:
        >>> product_code(1012100), product_code("85411000"), product_code("TOTAL")
        ('01012100', '85411000', 'TOTAL')
    """
    code = str(product).strip()
    if code.isdigit() and len(code) % 2 == 1:
        return "0" + code
    return code


# Fonction de génération des macros SQL équivalentes
def nomenclature_macros_sql(nomenclatures: Mapping[str, int]) -> List[str]:
    """Generate DuckDB macros equivalent to :func:`vintage_in_force`,
    :func:`classification_of`, :func:`product_code` and :func:`hs_vintage_of`.

    The macros are session-scoped (``TEMP``) so they never land in a catalog.
    ``vintage_in_force(y)`` returns ``NULL`` for a year preceding the first
    vintage (the Python function raises instead). ``classification_of`` applies
    ``product_code`` first, so it accepts codes stored as integers.

    Args:
        nomenclatures: Mapping vintage label -> entry-into-force year.

    Returns:
        Four ``CREATE OR REPLACE TEMP MACRO`` statements: ``product_code``,
        ``vintage_in_force``, ``classification_of`` (which calls both), then
        ``hs_vintage_of`` (see :func:`hs_vintage_of`).

    Examples:
        >>> sql = nomenclature_macros_sql({"HS1992": 1988, "HS2022": 2022})
        >>> print(sql[1])
        CREATE OR REPLACE TEMP MACRO vintage_in_force(y) AS CASE WHEN CAST(y AS INTEGER) >= 2022 THEN 'HS2022' WHEN CAST(y AS INTEGER) >= 1988 THEN 'HS1992' END
    """
    # Branches du plus récent au plus ancien : la première vérifiée l'emporte
    branches = " ".join(
        f"WHEN CAST(y AS INTEGER) >= {entry} THEN '{label}'"
        for label, entry in reversed(_sorted_vintages(nomenclatures))
    )
    return [
        "CREATE OR REPLACE TEMP MACRO product_code(p) AS CASE "
        "WHEN regexp_full_match(CAST(p AS VARCHAR), '[0-9]+') "
        "AND length(CAST(p AS VARCHAR)) % 2 = 1 THEN '0' || CAST(p AS VARCHAR) "
        "ELSE CAST(p AS VARCHAR) END",
        f"CREATE OR REPLACE TEMP MACRO vintage_in_force(y) AS CASE {branches} END",
        "CREATE OR REPLACE TEMP MACRO classification_of(p, y) AS CASE "
        "WHEN length(product_code(p)) = 8 THEN 'CN' || CAST(CAST(y AS INTEGER) AS VARCHAR) "
        "ELSE vintage_in_force(y) END",
        "CREATE OR REPLACE TEMP MACRO hs_vintage_of(c, y) AS CASE "
        "WHEN starts_with(CAST(c AS VARCHAR), 'CN') THEN vintage_in_force(y) "
        "ELSE CAST(c AS VARCHAR) END",
    ]


# Fonction de résolution de l'environnement Kedro
def resolve_env(env: Optional[str] = None) -> str:
    """Return the Kedro environment to load.

    Args:
        env: Explicit environment; when ``None``, ``KEDRO_ENV`` is used, and
            ``local`` (the default run environment of the project) when unset.

    Returns:
        The environment name.

    Examples:
        >>> resolve_env("demo")
        'demo'
    """
    if env:
        return env
    from kedro_pipeline.settings import CONFIG_LOADER_ARGS

    return os.environ.get(KEDRO_ENV_VARIABLE) or str(CONFIG_LOADER_ARGS["default_run_env"])


# Fonction de localisation de la source de configuration
def conf_source_path() -> Path:
    """Return the configuration directory of the project (``CONF_SOURCE``).

    Returns:
        ``<repository>/config`` when it exists next to the package, else the
        ``CONF_SOURCE`` directory of the working directory.

    Examples:
        >>> conf_source_path().name
        'config'
    """
    from kedro_pipeline.settings import CONF_SOURCE

    candidate = _REPO_ROOT / CONF_SOURCE
    return candidate if candidate.is_dir() else Path.cwd() / CONF_SOURCE


# Chargement mis en cache d'une section de configuration
@functools.lru_cache(maxsize=None)
def _cached_section(conf_source: str, env: str, key: str) -> Dict[str, Any]:
    """Load one configuration section (no copy: callers copy the result)."""
    from kedro.config import OmegaConfigLoader

    from kedro_pipeline.settings import CONFIG_LOADER_ARGS

    # Mêmes arguments que la session Kedro (settings.py, source unique)
    loader = OmegaConfigLoader(conf_source=conf_source, env=env, **CONFIG_LOADER_ARGS)
    return dict(loader[key])


# Fonction de chargement d'une section de configuration
def load_config_section(key: str, env: Optional[str] = None) -> Dict[str, Any]:
    """Load a configuration section merged as Kedro does (``base`` + environment).

    Args:
        key: Section key of the configuration loader (``"parameters"``,
            ``"experiments"``, ``"catalog"``…).
        env: Kedro environment (see :func:`resolve_env`).

    Returns:
        A deep copy of the merged section, interpolations resolved.

    Raises:
        KeyError: If ``key`` is not a configuration pattern of the project.
        kedro.config.MissingConfigException: If no file matches the section.

    Examples:
        >>> load_config_section("experiments", "base")["EXPERIMENTS"]["baci"]
        'trade-02-baci'
    """
    section = _cached_section(str(conf_source_path()), resolve_env(env), key)
    # Copie profonde : un appelant qui modifie le dictionnaire ne pollue pas le cache
    return copy.deepcopy(section)


# Fonction de chargement des paramètres
def load_parameters(env: Optional[str] = None) -> Dict[str, Any]:
    """Load the project parameters as a Kedro session would.

    Every ``config/<env>/parameters*.yml`` file holds one root key (``baci``,
    ``runtime``, ``serving``…); the environment files are merged "softly" into
    ``base`` (recursive merge of mappings, lists replaced).

    Args:
        env: Kedro environment; ``KEDRO_ENV``, else ``local``, when ``None``.

    Returns:
        The merged parameters, keyed by root (e.g. ``load_parameters()["baci"]``).

    Examples:
        >>> load_parameters("base")["runtime"]["ANALYSIS_START_YEAR"]["comtrade"]
        1994
        >>> load_parameters("demo")["serving"]["SCHEMA"]
        'demo_dashboard'
    """
    return load_config_section("parameters", env)


# Fonction de lecture du nom d'expérience MLflow d'un bloc d'étapes
def experiment_name(block: str, env: Optional[str] = None) -> str:
    """Return the MLflow experiment of a block of steps.

    Args:
        block: Block name, a key of ``EXPERIMENTS`` in ``experiments.yml``
            (``"downloads"``, ``"baci"``, ``"vulnerabilities"``, ``"serving"``).
        env: Kedro environment (see :func:`resolve_env`).

    Returns:
        ``MLFLOW_EXPERIMENT_NAME`` when set and not empty, else the configured
        name of the block.

    Raises:
        KeyError: If the block has no configured experiment.

    Examples:
        >>> experiment_name("serving", "demo")  # doctest: +SKIP
        'demo-trade-04-serving'
    """
    override = os.environ.get(EXPERIMENT_NAME_VARIABLE)
    if override:
        return override
    experiments = load_config_section("experiments", env).get("EXPERIMENTS") or {}
    if block not in experiments:
        raise KeyError(f"No MLflow experiment configured for block '{block}' (experiments.yml)")
    return str(experiments[block])


# Fonction de sélection des cibles BACI actives
def active_targets(targets: Optional[Mapping[str, Any]]) -> Dict[str, Any]:
    """Return the enabled BACI targets, in configuration order.

    An environment cannot remove a key of ``base`` (the parameter merge is
    recursive): it disables a vintage with a null entry, dropped here.

    Args:
        targets: ``baci.CLASSIFICATIONS.TARGETS`` (vintage -> target or ``None``).

    Returns:
        The non-null targets.

    Examples:
        >>> active_targets({"HS2022": None, "HS2017": {"RESULT_SCHEMA": "b"}})
        {'HS2017': {'RESULT_SCHEMA': 'b'}}
    """
    return {label: target for label, target in (targets or {}).items() if target is not None}


# Fonction de lecture d'un fichier de configuration explicite
def read_config_file(path: Any, root: Optional[str] = None) -> Dict[str, Any]:
    """Read one YAML configuration file given explicitly (tests, one-off runs).

    Args:
        path: Path of the YAML file.
        root: Root key of the block; when the document holds this single key
            (format of ``config/<env>/parameters_*.yml``) the block is
            returned, otherwise the whole document (historical format).

    Returns:
        The block, or the whole document.

    Raises:
        OSError: If the file cannot be read.

    Examples:
        >>> read_config_file("config/base/parameters_baci.yml", "baci")["BUCKET"]  # doctest: +SKIP
        'qbollietdgddi'
    """
    import yaml

    with open(path, "r", encoding="utf-8") as file:
        document = yaml.safe_load(file) or {}
    if root is not None and isinstance(document, Mapping) and list(document) == [root]:
        return dict(document[root])
    return dict(document)
