"""Pure helpers on the nomenclature vintages (PS-28.1, PD-20).

The single source of truth is ``runtime.NOMENCLATURES.HS``: a mapping from HS
vintage label to its entry-into-force year. Every function here is pure (no
I/O, no environment): the serving layer derives ``classification`` /
``hs_vintage`` / ``in_force`` from them while the result tables do not carry
those columns yet (PS-29.3), and the SQL macros generated by
:func:`nomenclature_macros_sql` evaluate the very same rule inside DuckDB.
"""
# Importation des modules
# Modules de base
from typing import List, Mapping, Tuple


# Fonction de tri des millésimes par année d'entrée en vigueur
def _sorted_vintages(nomenclatures: Mapping[str, int]) -> List[Tuple[str, int]]:
    """Return the ``(vintage, entry_year)`` pairs sorted by entry year.

    Args:
        nomenclatures: Mapping vintage label -> entry-into-force year.

    Returns:
        Pairs sorted by increasing entry year (ties broken by label).

    Raises:
        ValueError: If the mapping is empty.
    """
    # Vérification des arguments
    if not nomenclatures:
        raise ValueError("nomenclatures is empty: runtime.NOMENCLATURES.HS is required")
    return sorted(
        ((str(label), int(year)) for label, year in nomenclatures.items()),
        key=lambda item: (item[1], item[0]),
    )


# Fonction de détermination du millésime en vigueur une année donnée
def vintage_in_force(year: int, nomenclatures: Mapping[str, int]) -> str:
    """Return the HS vintage in force for ``year``.

    Args:
        year: Reference year.
        nomenclatures: Mapping vintage label -> entry-into-force year
            (``runtime.NOMENCLATURES.HS``).

    Returns:
        Label of the most recent vintage whose entry year is ``<= year``.

    Raises:
        ValueError: If ``year`` precedes the first vintage, or if the mapping
            is empty.

    Examples:
        >>> hs = {"HS1992": 1988, "HS1996": 1996, "HS2002": 2002, "HS2022": 2022}
        >>> vintage_in_force(1990, hs), vintage_in_force(2001, hs), vintage_in_force(2024, hs)
        ('HS1992', 'HS1996', 'HS2022')
    """
    vintages = _sorted_vintages(nomenclatures)
    # Dernier millésime entré en vigueur au plus tard l'année demandée
    eligible = [label for label, entry in vintages if entry <= int(year)]
    if not eligible:
        raise ValueError(
            f"No HS vintage in force in {year}: the first one enters into force "
            f"in {vintages[0][1]}"
        )
    return eligible[-1]


# Fonction de listage des millésimes historiques d'une année
def historical_vintages(year: int, nomenclatures: Mapping[str, int]) -> List[str]:
    """Return the vintages V with ``entry(V) <= year``, except the one in force.

    Args:
        year: Reference year.
        nomenclatures: Mapping vintage label -> entry-into-force year.

    Returns:
        Historical vintages, oldest first (empty when only one applies).

    Raises:
        ValueError: If ``year`` precedes the first vintage.

    Examples:
        >>> hs = {"HS1992": 1988, "HS1996": 1996, "HS2002": 2002, "HS2022": 2022}
        >>> historical_vintages(2024, hs)
        ['HS1992', 'HS1996', 'HS2002']
        >>> historical_vintages(1990, hs)
        []
    """
    in_force = vintage_in_force(year, nomenclatures)
    return [
        label
        for label, entry in _sorted_vintages(nomenclatures)
        if entry <= int(year) and label != in_force
    ]


# Fonction d'attribution de la nomenclature d'un code produit
def classification_of(product: str, year: int, nomenclatures: Mapping[str, int]) -> str:
    """Return the classification a product code belongs to in ``year`` (PD-20.3).

    Two-, four- and six-digit codes are HS codes of the vintage in force;
    eight-digit codes are Combined Nomenclature codes of that year.

    Args:
        product: Product code, as text or integer (see :func:`product_code`).
        year: Reference year.
        nomenclatures: Mapping vintage label -> entry-into-force year.

    Returns:
        ``"HSxxxx"`` for 2/4/6-digit codes, ``"CN<year>"`` for 8-digit codes.

    Raises:
        ValueError: If ``year`` precedes the first vintage.

    Examples:
        >>> hs = {"HS1992": 1988, "HS2017": 2017, "HS2022": 2022}
        >>> classification_of("854110", 2019, hs), classification_of("85411000", 2019, hs)
        ('HS2017', 'CN2019')
    """
    if len(product_code(product)) == 8:
        return f"CN{int(year)}"
    return vintage_in_force(year, nomenclatures)


# Fonction de restitution d'un code produit stocké en entier
def product_code(product: object) -> str:
    """Return a product code as text, restoring the leading zero lost by integer storage.

    Comext product codes are read as ``BIGINT`` by the download step, so
    chapters 01-09 lose their leading zero (``01012100`` -> ``1012100``). HS
    and CN codes have an even length (2, 4, 6, 8 digits): a numeric code of odd
    length is therefore left-padded by one zero. Non-numeric codes are kept.

    Args:
        product: Product code, as text or integer.

    Returns:
        The code as text, with its leading zero restored.

    Examples:
        >>> product_code(1012100), product_code("85411000"), product_code("TOTAL")
        ('01012100', '85411000', 'TOTAL')
    """
    code = str(product).strip()
    if code.isdigit() and len(code) % 2 == 1:
        return "0" + code
    return code


# Fonction de génération des macros SQL équivalentes (PS-29.3)
def nomenclature_macros_sql(nomenclatures: Mapping[str, int]) -> List[str]:
    """Generate DuckDB macros equivalent to :func:`vintage_in_force`,
    :func:`classification_of` and :func:`product_code`.

    The macros are session-scoped (``TEMP``) so they never land in a catalog.
    ``vintage_in_force(y)`` returns ``NULL`` for a year preceding the first
    vintage (the Python function raises instead). ``classification_of`` applies
    ``product_code`` first, so it accepts codes stored as integers.

    Args:
        nomenclatures: Mapping vintage label -> entry-into-force year.

    Returns:
        Three ``CREATE OR REPLACE TEMP MACRO`` statements: ``product_code``,
        ``vintage_in_force``, then ``classification_of`` (which calls both).

    Examples:
        >>> sql = nomenclature_macros_sql({"HS1992": 1988, "HS2022": 2022})
        >>> print(sql[1])
        CREATE OR REPLACE TEMP MACRO vintage_in_force(y) AS CASE WHEN CAST(y AS INTEGER) >= 2022 THEN 'HS2022' WHEN CAST(y AS INTEGER) >= 1988 THEN 'HS1992' END
    """
    # Branches du plus récent au plus ancien : la première vérifiée l'emporte
    branches = " ".join(
        f"WHEN CAST(y AS INTEGER) >= {entry} THEN '{label}'"
        for label, entry in reversed(_sorted_vintages(nomenclatures))
    )
    return [
        "CREATE OR REPLACE TEMP MACRO product_code(p) AS CASE "
        "WHEN regexp_full_match(CAST(p AS VARCHAR), '[0-9]+') "
        "AND length(CAST(p AS VARCHAR)) % 2 = 1 THEN '0' || CAST(p AS VARCHAR) "
        "ELSE CAST(p AS VARCHAR) END",
        f"CREATE OR REPLACE TEMP MACRO vintage_in_force(y) AS CASE {branches} END",
        "CREATE OR REPLACE TEMP MACRO classification_of(p, y) AS CASE "
        "WHEN length(product_code(p)) = 8 THEN 'CN' || CAST(CAST(y AS INTEGER) AS VARCHAR) "
        "ELSE vintage_in_force(y) END",
    ]
